#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PokeFinder.Resource", IsApplication=true)]

namespace PokeFinder
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0a0001
			public const int rarechooseArray = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int spinnerItems = 2131361792;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010017
			public const int adSize = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int adSizes = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int adUnitId = 2130771993;
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010014
			public const int buttonSize = 2130771988;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010013
			public const int circleCrop = 2130771987;
			
			// aapt resource value: 0x7f010015
			public const int colorScheme = 2130771989;
			
			// aapt resource value: 0x7f010012
			public const int imageAspectRatio = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatioAdjust = 2130771985;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010016
			public const int scopeUris = 2130771990;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05000e
			public const int common_action_bar_splitter = 2131034126;
			
			// aapt resource value: 0x7f050017
			public const int common_google_signin_btn_text_dark = 2131034135;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_signin_btn_text_dark_default = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int common_google_signin_btn_text_dark_disabled = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int common_google_signin_btn_text_dark_focused = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int common_google_signin_btn_text_dark_pressed = 2131034128;
			
			// aapt resource value: 0x7f050018
			public const int common_google_signin_btn_text_light = 2131034136;
			
			// aapt resource value: 0x7f050013
			public const int common_google_signin_btn_text_light_default = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int common_google_signin_btn_text_light_disabled = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int common_google_signin_btn_text_light_focused = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int common_google_signin_btn_text_light_pressed = 2131034132;
			
			// aapt resource value: 0x7f050019
			public const int common_plus_signin_btn_text_dark = 2131034137;
			
			// aapt resource value: 0x7f050006
			public const int common_plus_signin_btn_text_dark_default = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int common_plus_signin_btn_text_dark_disabled = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_plus_signin_btn_text_dark_focused = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int common_plus_signin_btn_text_dark_pressed = 2131034119;
			
			// aapt resource value: 0x7f05001a
			public const int common_plus_signin_btn_text_light = 2131034138;
			
			// aapt resource value: 0x7f05000a
			public const int common_plus_signin_btn_text_light_default = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int common_plus_signin_btn_text_light_disabled = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int common_plus_signin_btn_text_light_focused = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int common_plus_signin_btn_text_light_pressed = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int place_autocomplete_prediction_primary_text = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int place_autocomplete_prediction_primary_text_highlight = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int place_autocomplete_prediction_secondary_text = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int place_autocomplete_search_hint = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int place_autocomplete_search_text = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int place_autocomplete_separator = 2131034117;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int place_autocomplete_button_padding = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int place_autocomplete_powered_by_google_height = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int place_autocomplete_powered_by_google_start = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int place_autocomplete_prediction_height = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int place_autocomplete_prediction_horizontal_margin = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int place_autocomplete_prediction_primary_text = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int place_autocomplete_prediction_secondary_text = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int place_autocomplete_progress_horizontal_margin = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int place_autocomplete_progress_size = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int place_autocomplete_separator_start = 2131099655;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_ic_googleplayservices = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_plus_signin_btn_icon_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_plus_signin_btn_icon_dark_focused = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_plus_signin_btn_icon_dark_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_plus_signin_btn_icon_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_plus_signin_btn_icon_light_disabled = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_plus_signin_btn_icon_light_focused = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_light_normal = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_light_pressed = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_text_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_text_dark_disabled = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_text_dark_focused = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_text_dark_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_text_dark_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_text_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_text_light_disabled = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_text_light_focused = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_light_normal = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_light_pressed = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Icon = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Icon1 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Icon2 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Icon3 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int Icon4 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int Icon5 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int InfoWindow = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int LocationMarker = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int LocationMarker1 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int LocationMarker2 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int LocationMarker3 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int LocationMarker4 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int LocationMarker5 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int places_ic_clear = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int places_ic_search = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int powered_by_google_dark = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int powered_by_google_light = 2130837562;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0c0005
			public const int adjust_height = 2131492869;
			
			// aapt resource value: 0x7f0c0006
			public const int adjust_width = 2131492870;
			
			// aapt resource value: 0x7f0c0014
			public const int adsLayout = 2131492884;
			
			// aapt resource value: 0x7f0c000a
			public const int auto = 2131492874;
			
			// aapt resource value: 0x7f0c000f
			public const int btnBugSubmit = 2131492879;
			
			// aapt resource value: 0x7f0c0013
			public const int buttonsLayout = 2131492883;
			
			// aapt resource value: 0x7f0c000b
			public const int dark = 2131492875;
			
			// aapt resource value: 0x7f0c0019
			public const int distanceText = 2131492889;
			
			// aapt resource value: 0x7f0c000d
			public const int emailText = 2131492877;
			
			// aapt resource value: 0x7f0c0010
			public const int findLayout = 2131492880;
			
			// aapt resource value: 0x7f0c0011
			public const int firstSpinner = 2131492881;
			
			// aapt resource value: 0x7f0c001a
			public const int fragmentContainer = 2131492890;
			
			// aapt resource value: 0x7f0c0029
			public const int help = 2131492905;
			
			// aapt resource value: 0x7f0c0000
			public const int hybrid = 2131492864;
			
			// aapt resource value: 0x7f0c0007
			public const int icon_only = 2131492871;
			
			// aapt resource value: 0x7f0c0015
			public const int imageView1 = 2131492885;
			
			// aapt resource value: 0x7f0c000c
			public const int light = 2131492876;
			
			// aapt resource value: 0x7f0c0016
			public const int linearLayout1 = 2131492886;
			
			// aapt resource value: 0x7f0c0025
			public const int mapContainer = 2131492901;
			
			// aapt resource value: 0x7f0c0012
			public const int mapLayout = 2131492882;
			
			// aapt resource value: 0x7f0c000e
			public const int messageText = 2131492878;
			
			// aapt resource value: 0x7f0c0017
			public const int nameText = 2131492887;
			
			// aapt resource value: 0x7f0c0001
			public const int none = 2131492865;
			
			// aapt resource value: 0x7f0c0002
			public const int normal = 2131492866;
			
			// aapt resource value: 0x7f0c001d
			public const int place_autocomplete_clear_button = 2131492893;
			
			// aapt resource value: 0x7f0c001f
			public const int place_autocomplete_powered_by_google = 2131492895;
			
			// aapt resource value: 0x7f0c0021
			public const int place_autocomplete_prediction_primary_text = 2131492897;
			
			// aapt resource value: 0x7f0c0022
			public const int place_autocomplete_prediction_secondary_text = 2131492898;
			
			// aapt resource value: 0x7f0c0020
			public const int place_autocomplete_progress = 2131492896;
			
			// aapt resource value: 0x7f0c001b
			public const int place_autocomplete_search_button = 2131492891;
			
			// aapt resource value: 0x7f0c001c
			public const int place_autocomplete_search_input = 2131492892;
			
			// aapt resource value: 0x7f0c001e
			public const int place_autocomplete_separator = 2131492894;
			
			// aapt resource value: 0x7f0c0024
			public const int pokemonNameText1 = 2131492900;
			
			// aapt resource value: 0x7f0c0028
			public const int report_bug = 2131492904;
			
			// aapt resource value: 0x7f0c0003
			public const int satellite = 2131492867;
			
			// aapt resource value: 0x7f0c0008
			public const int standard = 2131492872;
			
			// aapt resource value: 0x7f0c0027
			public const int submitAdLayout = 2131492903;
			
			// aapt resource value: 0x7f0c0026
			public const int submitButton = 2131492902;
			
			// aapt resource value: 0x7f0c0023
			public const int submitLayout = 2131492899;
			
			// aapt resource value: 0x7f0c0004
			public const int terrain = 2131492868;
			
			// aapt resource value: 0x7f0c0018
			public const int timeText = 2131492888;
			
			// aapt resource value: 0x7f0c0009
			public const int wide = 2131492873;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int google_play_services_version = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EmailForm = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FindPokemon = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int infowindow = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int place_autocomplete_fragment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int place_autocomplete_item_powered_by_google = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int place_autocomplete_item_prediction = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int place_autocomplete_progress = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SubmitPokemon = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int MainMenu = 2131427328;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int gtm_analytics = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070028
			public const int ApplicationName = 2131165224;
			
			// aapt resource value: 0x7f070027
			public const int Hello = 2131165223;
			
			// aapt resource value: 0x7f070023
			public const int accept = 2131165219;
			
			// aapt resource value: 0x7f070003
			public const int auth_google_play_services_client_facebook_display_name = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int auth_google_play_services_client_google_display_name = 2131165186;
			
			// aapt resource value: 0x7f07001a
			public const int common_google_play_services_api_unavailable_text = 2131165210;
			
			// aapt resource value: 0x7f07000c
			public const int common_google_play_services_enable_button = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int common_google_play_services_enable_text = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int common_google_play_services_enable_title = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int common_google_play_services_install_button = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int common_google_play_services_install_text_phone = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int common_google_play_services_install_text_tablet = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int common_google_play_services_install_title = 2131165190;
			
			// aapt resource value: 0x7f070015
			public const int common_google_play_services_invalid_account_text = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int common_google_play_services_invalid_account_title = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int common_google_play_services_network_error_text = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int common_google_play_services_network_error_title = 2131165202;
			
			// aapt resource value: 0x7f070005
			public const int common_google_play_services_notification_ticker = 2131165189;
			
			// aapt resource value: 0x7f07001e
			public const int common_google_play_services_restricted_profile_text = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int common_google_play_services_restricted_profile_title = 2131165213;
			
			// aapt resource value: 0x7f07001c
			public const int common_google_play_services_sign_in_failed_text = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int common_google_play_services_sign_in_failed_title = 2131165211;
			
			// aapt resource value: 0x7f070004
			public const int common_google_play_services_unknown_issue = 2131165188;
			
			// aapt resource value: 0x7f070017
			public const int common_google_play_services_unsupported_text = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int common_google_play_services_unsupported_title = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int common_google_play_services_update_button = 2131165208;
			
			// aapt resource value: 0x7f07000e
			public const int common_google_play_services_update_text = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int common_google_play_services_update_title = 2131165197;
			
			// aapt resource value: 0x7f070011
			public const int common_google_play_services_updating_text = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int common_google_play_services_updating_title = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int common_google_play_services_wear_update_text = 2131165199;
			
			// aapt resource value: 0x7f070019
			public const int common_open_on_phone = 2131165209;
			
			// aapt resource value: 0x7f07001f
			public const int common_signin_button_text = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int common_signin_button_text_long = 2131165216;
			
			// aapt resource value: 0x7f070026
			public const int create_calendar_message = 2131165222;
			
			// aapt resource value: 0x7f070025
			public const int create_calendar_title = 2131165221;
			
			// aapt resource value: 0x7f070024
			public const int decline = 2131165220;
			
			// aapt resource value: 0x7f070029
			public const int google_maps_key = 2131165225;
			
			// aapt resource value: 0x7f070001
			public const int place_autocomplete_clear_button = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int place_autocomplete_search_hint = 2131165184;
			
			// aapt resource value: 0x7f07002a
			public const int rareChoose = 2131165226;
			
			// aapt resource value: 0x7f070022
			public const int store_picture_message = 2131165218;
			
			// aapt resource value: 0x7f070021
			public const int store_picture_title = 2131165217;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int Theme_IAPTheme = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
