#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PokeFinder.Resource", IsApplication=true)]

namespace PokeFinder
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010017
			public const int adSize = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int adSizes = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int adUnitId = 2130771993;
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010014
			public const int buttonSize = 2130771988;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010013
			public const int circleCrop = 2130771987;
			
			// aapt resource value: 0x7f010015
			public const int colorScheme = 2130771989;
			
			// aapt resource value: 0x7f010012
			public const int imageAspectRatio = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatioAdjust = 2130771985;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010016
			public const int scopeUris = 2130771990;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f04000e
			public const int common_action_bar_splitter = 2130968590;
			
			// aapt resource value: 0x7f040017
			public const int common_google_signin_btn_text_dark = 2130968599;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_signin_btn_text_dark_default = 2130968591;
			
			// aapt resource value: 0x7f040011
			public const int common_google_signin_btn_text_dark_disabled = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int common_google_signin_btn_text_dark_focused = 2130968594;
			
			// aapt resource value: 0x7f040010
			public const int common_google_signin_btn_text_dark_pressed = 2130968592;
			
			// aapt resource value: 0x7f040018
			public const int common_google_signin_btn_text_light = 2130968600;
			
			// aapt resource value: 0x7f040013
			public const int common_google_signin_btn_text_light_default = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int common_google_signin_btn_text_light_disabled = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int common_google_signin_btn_text_light_focused = 2130968598;
			
			// aapt resource value: 0x7f040014
			public const int common_google_signin_btn_text_light_pressed = 2130968596;
			
			// aapt resource value: 0x7f040019
			public const int common_plus_signin_btn_text_dark = 2130968601;
			
			// aapt resource value: 0x7f040006
			public const int common_plus_signin_btn_text_dark_default = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int common_plus_signin_btn_text_dark_disabled = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int common_plus_signin_btn_text_dark_focused = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int common_plus_signin_btn_text_dark_pressed = 2130968583;
			
			// aapt resource value: 0x7f04001a
			public const int common_plus_signin_btn_text_light = 2130968602;
			
			// aapt resource value: 0x7f04000a
			public const int common_plus_signin_btn_text_light_default = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int common_plus_signin_btn_text_light_disabled = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int common_plus_signin_btn_text_light_focused = 2130968589;
			
			// aapt resource value: 0x7f04000b
			public const int common_plus_signin_btn_text_light_pressed = 2130968587;
			
			// aapt resource value: 0x7f040002
			public const int place_autocomplete_prediction_primary_text = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int place_autocomplete_prediction_primary_text_highlight = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int place_autocomplete_prediction_secondary_text = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int place_autocomplete_search_hint = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int place_autocomplete_search_text = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int place_autocomplete_separator = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int place_autocomplete_button_padding = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int place_autocomplete_powered_by_google_height = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int place_autocomplete_powered_by_google_start = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int place_autocomplete_prediction_height = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int place_autocomplete_prediction_horizontal_margin = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int place_autocomplete_prediction_primary_text = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int place_autocomplete_prediction_secondary_text = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int place_autocomplete_progress_horizontal_margin = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int place_autocomplete_progress_size = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int place_autocomplete_separator_start = 2131034119;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_ic_googleplayservices = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_plus_signin_btn_icon_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_plus_signin_btn_icon_dark_focused = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_plus_signin_btn_icon_dark_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_plus_signin_btn_icon_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_plus_signin_btn_icon_light_disabled = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_plus_signin_btn_icon_light_focused = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_light_normal = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_light_pressed = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_text_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_text_dark_disabled = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_text_dark_focused = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_text_dark_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_text_dark_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_text_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_text_light_disabled = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_text_light_focused = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_light_normal = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_light_pressed = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Icon = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int LocationMarker = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int places_ic_clear = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int places_ic_search = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int powered_by_google_dark = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int powered_by_google_light = 2130837551;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0005
			public const int adjust_height = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int adjust_width = 2131361798;
			
			// aapt resource value: 0x7f0a000a
			public const int auto = 2131361802;
			
			// aapt resource value: 0x7f0a000f
			public const int btnBugSubmit = 2131361807;
			
			// aapt resource value: 0x7f0a000b
			public const int dark = 2131361803;
			
			// aapt resource value: 0x7f0a000d
			public const int emailText = 2131361805;
			
			// aapt resource value: 0x7f0a0010
			public const int fragmentContainer = 2131361808;
			
			// aapt resource value: 0x7f0a001f
			public const int help = 2131361823;
			
			// aapt resource value: 0x7f0a0000
			public const int hybrid = 2131361792;
			
			// aapt resource value: 0x7f0a0007
			public const int icon_only = 2131361799;
			
			// aapt resource value: 0x7f0a000c
			public const int light = 2131361804;
			
			// aapt resource value: 0x7f0a001b
			public const int mapContainer = 2131361819;
			
			// aapt resource value: 0x7f0a000e
			public const int messageText = 2131361806;
			
			// aapt resource value: 0x7f0a0001
			public const int none = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int normal = 2131361794;
			
			// aapt resource value: 0x7f0a0013
			public const int place_autocomplete_clear_button = 2131361811;
			
			// aapt resource value: 0x7f0a0015
			public const int place_autocomplete_powered_by_google = 2131361813;
			
			// aapt resource value: 0x7f0a0017
			public const int place_autocomplete_prediction_primary_text = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int place_autocomplete_prediction_secondary_text = 2131361816;
			
			// aapt resource value: 0x7f0a0016
			public const int place_autocomplete_progress = 2131361814;
			
			// aapt resource value: 0x7f0a0011
			public const int place_autocomplete_search_button = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int place_autocomplete_search_input = 2131361810;
			
			// aapt resource value: 0x7f0a0014
			public const int place_autocomplete_separator = 2131361812;
			
			// aapt resource value: 0x7f0a001a
			public const int pokemonNameText1 = 2131361818;
			
			// aapt resource value: 0x7f0a001e
			public const int report_bug = 2131361822;
			
			// aapt resource value: 0x7f0a0003
			public const int satellite = 2131361795;
			
			// aapt resource value: 0x7f0a0008
			public const int standard = 2131361800;
			
			// aapt resource value: 0x7f0a001d
			public const int submitAdLayout = 2131361821;
			
			// aapt resource value: 0x7f0a001c
			public const int submitButton = 2131361820;
			
			// aapt resource value: 0x7f0a0019
			public const int submitLayout = 2131361817;
			
			// aapt resource value: 0x7f0a0004
			public const int terrain = 2131361796;
			
			// aapt resource value: 0x7f0a0009
			public const int wide = 2131361801;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int EmailForm = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FindPokemon = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int place_autocomplete_fragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int place_autocomplete_item_powered_by_google = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int place_autocomplete_item_prediction = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int place_autocomplete_progress = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SubmitPokemon = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int MainMenu = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060028
			public const int ApplicationName = 2131099688;
			
			// aapt resource value: 0x7f060027
			public const int Hello = 2131099687;
			
			// aapt resource value: 0x7f060023
			public const int accept = 2131099683;
			
			// aapt resource value: 0x7f060003
			public const int auth_google_play_services_client_facebook_display_name = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int auth_google_play_services_client_google_display_name = 2131099650;
			
			// aapt resource value: 0x7f06001a
			public const int common_google_play_services_api_unavailable_text = 2131099674;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_enable_button = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_enable_text = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_enable_title = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_install_button = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_install_text_phone = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_install_text_tablet = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_install_title = 2131099654;
			
			// aapt resource value: 0x7f060015
			public const int common_google_play_services_invalid_account_text = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int common_google_play_services_invalid_account_title = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int common_google_play_services_network_error_text = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int common_google_play_services_network_error_title = 2131099666;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_notification_ticker = 2131099653;
			
			// aapt resource value: 0x7f06001e
			public const int common_google_play_services_restricted_profile_text = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int common_google_play_services_restricted_profile_title = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int common_google_play_services_sign_in_failed_text = 2131099676;
			
			// aapt resource value: 0x7f06001b
			public const int common_google_play_services_sign_in_failed_title = 2131099675;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_unknown_issue = 2131099652;
			
			// aapt resource value: 0x7f060017
			public const int common_google_play_services_unsupported_text = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int common_google_play_services_unsupported_title = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int common_google_play_services_update_button = 2131099672;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_update_text = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_update_title = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int common_google_play_services_updating_text = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_updating_title = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_wear_update_text = 2131099663;
			
			// aapt resource value: 0x7f060019
			public const int common_open_on_phone = 2131099673;
			
			// aapt resource value: 0x7f06001f
			public const int common_signin_button_text = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int common_signin_button_text_long = 2131099680;
			
			// aapt resource value: 0x7f060026
			public const int create_calendar_message = 2131099686;
			
			// aapt resource value: 0x7f060025
			public const int create_calendar_title = 2131099685;
			
			// aapt resource value: 0x7f060024
			public const int decline = 2131099684;
			
			// aapt resource value: 0x7f060029
			public const int google_maps_key = 2131099689;
			
			// aapt resource value: 0x7f060001
			public const int place_autocomplete_clear_button = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int place_autocomplete_search_hint = 2131099648;
			
			// aapt resource value: 0x7f060022
			public const int store_picture_message = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int store_picture_title = 2131099681;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Theme_IAPTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
